"""add_files_column_to_releases

Revision ID: 67000ee5b7cd
Revises: 057a73d850e6
Create Date: 2026-05-04 23:48:07.317716

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67000ee5b7cd"
down_revision: str | None = "057a73d850e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("releases", sa.Column("files", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("releases", "files")
    # ### end Alembic commands ###
