"""add_perf_indexes

Revision ID: 3e80f5eb8ad3
Revises: 85be358dde52
Create Date: 2026-05-05 14:51:55.154102

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3e80f5eb8ad3"
down_revision: str | None = "85be358dde52"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_activity_logs_event_type", "activity_logs", ["event_type"], unique=False)
    op.create_index("ix_rules_enabled", "rules", ["is_enabled"], unique=False)
    op.create_index("ix_rules_type", "rules", ["rule_type"], unique=False)
    op.create_index(
        "ix_staged_torrents_request_id", "staged_torrents", ["request_id"], unique=False
    )
    op.create_index("ix_staged_torrents_status", "staged_torrents", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_staged_torrents_status", table_name="staged_torrents")
    op.drop_index("ix_staged_torrents_request_id", table_name="staged_torrents")
    op.drop_index("ix_rules_type", table_name="rules")
    op.drop_index("ix_rules_enabled", table_name="rules")
    op.drop_index("ix_activity_logs_event_type", table_name="activity_logs")
    # ### end Alembic commands ###
