"""initial_migration

Revision ID: 057a73d850e6
Revises:
Create Date: 2026-04-21 10:57:50.426836

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "057a73d850e6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plex_scan_state",
        sa.Column("job_name", sa.String(length=100), nullable=False),
        sa.Column("lock_owner", sa.String(length=255), nullable=True),
        sa.Column("lock_acquired_at", sa.DateTime(), nullable=True),
        sa.Column("lock_expires_at", sa.DateTime(), nullable=True),
        sa.Column("last_started_at", sa.DateTime(), nullable=True),
        sa.Column("last_finished_at", sa.DateTime(), nullable=True),
        sa.Column("last_success_at", sa.DateTime(), nullable=True),
        sa.Column("checkpoint_at", sa.DateTime(), nullable=True),
        sa.Column("last_error", sa.String(length=1000), nullable=True),
        sa.Column("metrics_payload", sa.JSON(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("job_name"),
    )
    op.create_table(
        "requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("media_type", sa.Enum("MOVIE", "TV", name="mediatype"), nullable=False),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("tvdb_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("requested_seasons", sa.String(length=100), nullable=True),
        sa.Column("requested_episodes", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "RECEIVED",
                "SEARCHING",
                "PENDING",
                "UNRELEASED",
                "STAGED",
                "DOWNLOADING",
                "COMPLETED",
                "FAILED",
                "AVAILABLE",
                "PARTIALLY_AVAILABLE",
                "DENIED",
                name="requeststatus",
            ),
            nullable=False,
        ),
        sa.Column("requester_username", sa.String(length=255), nullable=True),
        sa.Column("requester_email", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("overseerr_request_id", sa.Integer(), nullable=True),
        sa.Column("rejection_reason", sa.String(length=500), nullable=True),
        sa.Column("plex_rating_key", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_index("ix_requests_created_at", "requests", ["created_at"], unique=False)
    op.create_index("ix_requests_media_type", "requests", ["media_type"], unique=False)
    op.create_index("ix_requests_status", "requests", ["status"], unique=False)
    op.create_table(
        "rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "rule_type",
            sa.Enum("EXCLUSION", "REQUIREMENT", "SCORER", "SIZE_LIMIT", name="ruletype"),
            nullable=False,
        ),
        sa.Column("media_scope", sa.String(length=20), nullable=False),
        sa.Column("pattern", sa.String(length=500), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("min_size_gb", sa.Float(), nullable=True),
        sa.Column("max_size_gb", sa.Float(), nullable=True),
        sa.Column("tv_target", sa.Enum("EPISODE", "SEASON_PACK", name="tvtarget"), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "staged_torrents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=True),
        sa.Column("torrent_path", sa.String(length=500), nullable=False),
        sa.Column("json_path", sa.String(length=500), nullable=False),
        sa.Column("original_filename", sa.String(length=500), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("indexer", sa.String(length=255), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("magnet_url", sa.Text(), nullable=True),
        sa.Column("selection_source", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("replaced_by_id", sa.Integer(), nullable=True),
        sa.Column("replaced_at", sa.DateTime(), nullable=True),
        sa.Column("replacement_reason", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["replaced_by_id"],
            ["staged_torrents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "activity_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=True),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_activity_logs_created_at", "activity_logs", ["created_at"], unique=False)
    op.create_index("ix_activity_logs_request_id", "activity_logs", ["request_id"], unique=False)
    op.create_table(
        "pending_queue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("next_retry_at", sa.DateTime(), nullable=False),
        sa.Column("last_error", sa.String(length=1000), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id"),
    )
    op.create_index(
        "ix_pending_queue_next_retry_at", "pending_queue", ["next_retry_at"], unique=False
    )
    op.create_table(
        "releases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("seeders", sa.Integer(), nullable=False),
        sa.Column("leechers", sa.Integer(), nullable=False),
        sa.Column("download_url", sa.Text(), nullable=False),
        sa.Column("magnet_url", sa.Text(), nullable=True),
        sa.Column("info_hash", sa.String(length=64), nullable=True),
        sa.Column("indexer", sa.String(length=255), nullable=False),
        sa.Column("publish_date", sa.DateTime(), nullable=True),
        sa.Column("resolution", sa.String(length=20), nullable=True),
        sa.Column("codec", sa.String(length=50), nullable=True),
        sa.Column("release_group", sa.String(length=100), nullable=True),
        sa.Column("season_number", sa.Integer(), nullable=True),
        sa.Column("episode_number", sa.Integer(), nullable=True),
        sa.Column("season_coverage", sa.String(length=100), nullable=True),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("passed_rules", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_releases_request_id", "releases", ["request_id"], unique=False)
    op.create_index(
        "ix_releases_request_season_episode",
        "releases",
        ["request_id", "season_number", "episode_number"],
        unique=False,
    )
    op.create_index("ix_releases_score", "releases", ["score"], unique=False)
    op.create_table(
        "seasons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=False),
        sa.Column("season_number", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "RECEIVED",
                "SEARCHING",
                "PENDING",
                "UNRELEASED",
                "STAGED",
                "DOWNLOADING",
                "COMPLETED",
                "FAILED",
                "AVAILABLE",
                "PARTIALLY_AVAILABLE",
                "DENIED",
                name="requeststatus",
            ),
            nullable=False,
        ),
        sa.Column("synced_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id", "season_number", name="uq_seasons_request_season"),
    )
    op.create_index("ix_seasons_request_id", "seasons", ["request_id"], unique=False)
    op.create_table(
        "episodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("episode_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("air_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "RECEIVED",
                "SEARCHING",
                "PENDING",
                "UNRELEASED",
                "STAGED",
                "DOWNLOADING",
                "COMPLETED",
                "FAILED",
                "AVAILABLE",
                "PARTIALLY_AVAILABLE",
                "DENIED",
                name="requeststatus",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["seasons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("season_id", "episode_number", name="uq_episodes_season_episode"),
    )
    op.create_index("ix_episodes_season_id", "episodes", ["season_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_episodes_season_id", table_name="episodes")
    op.drop_table("episodes")
    op.drop_index("ix_seasons_request_id", table_name="seasons")
    op.drop_table("seasons")
    op.drop_index("ix_releases_score", table_name="releases")
    op.drop_index("ix_releases_request_season_episode", table_name="releases")
    op.drop_index("ix_releases_request_id", table_name="releases")
    op.drop_table("releases")
    op.drop_index("ix_pending_queue_next_retry_at", table_name="pending_queue")
    op.drop_table("pending_queue")
    op.drop_index("ix_activity_logs_request_id", table_name="activity_logs")
    op.drop_index("ix_activity_logs_created_at", table_name="activity_logs")
    op.drop_table("activity_logs")
    op.drop_table("staged_torrents")
    op.drop_table("settings")
    op.drop_table("rules")
    op.drop_index("ix_requests_status", table_name="requests")
    op.drop_index("ix_requests_media_type", table_name="requests")
    op.drop_index("ix_requests_created_at", table_name="requests")
    op.drop_table("requests")
    op.drop_table("plex_scan_state")
    # ### end Alembic commands ###
