"""Initial migration - create all tables

Revision ID: bc9c8cfbe08b
Revises:
Create Date: 2026-04-05 15:56:01.992819

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc9c8cfbe08b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "releases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("seeders", sa.Integer(), nullable=False),
        sa.Column("leechers", sa.Integer(), nullable=False),
        sa.Column("download_url", sa.Text(), nullable=False),
        sa.Column("magnet_url", sa.Text(), nullable=True),
        sa.Column("info_hash", sa.String(length=64), nullable=True),
        sa.Column("indexer", sa.String(length=255), nullable=False),
        sa.Column("publish_date", sa.DateTime(), nullable=True),
        sa.Column("resolution", sa.String(length=20), nullable=True),
        sa.Column("codec", sa.String(length=50), nullable=True),
        sa.Column("release_group", sa.String(length=100), nullable=True),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("passed_rules", sa.Boolean(), nullable=False),
        sa.Column("is_downloaded", sa.Boolean(), nullable=False),
        sa.Column("downloaded_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("media_type", sa.Enum("MOVIE", "TV", name="mediatype"), nullable=False),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("tvdb_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("requested_seasons", sa.String(length=100), nullable=True),
        sa.Column("requested_episodes", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "RECEIVED",
                "SEARCHING",
                "PENDING",
                "STAGED",
                "DOWNLOADING",
                "COMPLETED",
                "FAILED",
                name="requeststatus",
            ),
            nullable=False,
        ),
        sa.Column("requester_username", sa.String(length=255), nullable=True),
        sa.Column("requester_email", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_table(
        "rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "rule_type",
            sa.Enum("EXCLUSION", "REQUIREMENT", "SCORER", name="ruletype"),
            nullable=False,
        ),
        sa.Column("pattern", sa.String(length=500), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "staged_torrents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=True),
        sa.Column("torrent_path", sa.String(length=500), nullable=False),
        sa.Column("json_path", sa.String(length=500), nullable=False),
        sa.Column("original_filename", sa.String(length=500), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("indexer", sa.String(length=255), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("magnet_url", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pending_queue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("next_retry_at", sa.DateTime(), nullable=False),
        sa.Column("last_error", sa.String(length=1000), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pending_queue")
    op.drop_table("staged_torrents")
    op.drop_table("settings")
    op.drop_table("rules")
    op.drop_table("requests")
    op.drop_table("releases")
    # ### end Alembic commands ###
